name:  Zhi麽Shi频
on:
  workflow_dispatch:
  schedule:
     - cron: '48 */1 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/love-pig-pig/Daily-tasks.git ~/Daily-tasks
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Daily-tasks
          git checkout No-Fork
          npm install
      - name: '运行 【芝麻视频】'
        run: |
          cd ~/Daily-tasks
          node Task/zhima.js
        env:
             ZM_zhimabody: ${{ secrets.ZM_zhimabody }}
             ZM_zhimatxbody: ${{ secrets.ZM_zhimatxbody }}
             ZM_CASH: ${{ secrets.ZM_CASH }}
             TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
             TG_USER_ID: ${{ secrets.TG_USER_ID }}

